version: '3.8'

services:
  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  pharmacy-service:
    build: ./pharmacy-service
    container_name: pharmacy-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres

  medicine-service:
    build: ./medicine-service
    container_name: medicine-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - rabbitmq

  queue-service:
    build: ./queue-service
    container_name: queue-service
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq

  cache-service:
    build: ./cache-service
    container_name: cache-service
    ports:
      - "8087:8087"
    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - authentication-service
      - doctor-service
      - pharmacy-service
      - medicine-service
      - notification-service
      - queue-service
      - cache-service

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prescription_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
